name: Generate videos.json

on:
  push:
    paths:
      - 'videos/**'
  workflow_dispatch:  # позволяет запускать вручную из GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Клонируем репозиторий
        uses: actions/checkout@v4

      - name: 📦 Устанавливаем Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ▶️ Запускаем генерацию videos.json
        run: node generate-videos-json.js

      - name: 💾 Коммитим обновлённый файл
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: 'auto: обновлён videos.json'
          add: 'videos/videos.json'
